### ISSUE TITLE
Part of the title bar showing

### ISSUE THREAD

**Issue by ZooM2198** [Catgrills/Melbourne-R#2]
Hi there, just want to say that your CSS is great mate.

I've installed it and got an issue where part of my Windows 10 Visual Style is interrupting the CSS. Also, the close/minimize/maximize icons aren't like your screenshot. Any idea why this could be? The title bar is disabled.

![css](https://user-images.githubusercontent.com/39165655/39880781-abbfaa4e-5476-11e8-8c64-8856ac592c57.png)

The Windows Visual Style I'm using is https://undefinist.deviantart.com/art/OBLIQ-VS-10-647408322

**Comment by ZooM2198** [comment]
OK, I figured out why the theme was interuppting, I had to enable 'Light' theme from the customize menu instead of 'Default'. I guess it's just the buttons now.

![css2](https://user-images.githubusercontent.com/39165655/39881023-7566989e-5477-11e8-8039-3fd5e341ece3.png)

**Comment by ZooM2198** [comment]
Feel like an idiot now, found this code that did the trick

`/* Hide min, max, close in title bar */

#titlebar-min, #titlebar-max, #titlebar-close
{ display: none !important; }

/* Hide minimize, restore, close in full screen */

#minimize-button, #restore-button, #close-button
{ display: none !important; }`

Sorry for wasting your time mate

**Comment by Catgrills** [comment]
Not a problem dude, just glad you solved these issues.
